[build]
  publish = "."

# Serve audio files with proper headers
[[headers]]
  for = "/public/*.mp3"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "audio/mpeg"

# Serve audio files from root path too (since your JS references /sound1.mp3)
[[headers]]
  for = "/*.mp3"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "audio/mpeg"

# General security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Redirect audio files from root to public folder
[[redirects]]
  from = "/sound1.mp3"
  to = "/public/sound1.mp3"
  status = 200

[[redirects]]
  from = "/sound2.mp3"
  to = "/public/sound2.mp3"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200